removing shadow run.py

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -81,14 +81,15 @@ Vagrant.configure("2") do |config|
         mkdir /work/docker
         sed -i 's/^OPTIONS=.*//' /etc/sysconfig/docker
         echo 'OPTIONS="--default-ulimit nofile=1024:4096 -g /work/docker"' >> /etc/sysconfig/docker
-        usermod -a -G docker ec2-user
         service docker start
+        usermod -aG docker ec2-user
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "install docker-compose", inline: <<-SHELL
         echo "Install docker-compose"
-        curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
-        chmod +x /usr/local/bin/docker-compose
+        curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) \
+            -o /usr/bin/docker-compose
+        chmod +x /usr/bin/docker-compose
     SHELL
         
     config.vm.provision "shell", privileged: false, name: "install Singularity", inline: <<-SHELL
@@ -117,14 +118,14 @@ Vagrant.configure("2") do |config|
     SHELL
         
     config.vm.provision "shell", privileged: false, name: "docker login", inline: <<-SHELL
-        sudo docker login quay.io -u $(cut -d' ' -f1 ~/.docker/creds.txt) \
-                                  -p $(cut -d' ' -f2 ~/.docker/creds.txt)
+        docker login quay.io -u $(cut -d' ' -f1 ~/.docker/creds.txt) \
+                             -p $(cut -d' ' -f2 ~/.docker/creds.txt)
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "recount-pump image", inline: <<-SHELL
         SKIP_BUILD=0
         if [ ${SKIP_BUILD} = 0 ] ; then
-            cd /work/recount-pump && sudo ./build.sh && sudo ./push.sh
+            cd /work/recount-pump && ./build.sh && ./push.sh
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY benlangmead/recount-pump built and pushed"
             else
@@ -178,7 +179,7 @@ Vagrant.configure("2") do |config|
                 echo "------------------------------------------------------"
                 echo "Building and pushing (\"$FLOW\")"
                 echo "------------------------------------------------------"
-                cd ${FLOWDIR} && sudo ../common/build.sh && sudo ../common/push.sh
+                cd ${FLOWDIR} && ../common/build.sh && ../common/push.sh
                 if [ $? -eq 0 ] ; then
                     echo "===HAPPY ${IMAGE} built and pushed"
                 else
@@ -189,24 +190,23 @@ Vagrant.configure("2") do |config|
             echo "------------------------------------------------------"
             echo "Test-running Docker (\"$FLOW\")"
             echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ../common/run.py \
+            cd ${FLOWDIR} && ../../src/run.py \
                 --input ../common/accessions.txt \
                 --image ${IMAGE} \
                 --ini ~/.recount/cluster_docker.ini \
-                --sudo \
                 --name docker-test-${FLOW}
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY ${IMAGE} ran in Docker"
             else
                 echo "===SAD ERROR running ${IMAGE} in Docker"
             fi
-            find /work/recount-temp-docker/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
-            cat ${FLOWDIR}/outmd5.txt
+            #find /work/recount-temp-docker/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
+            #cat ${FLOWDIR}/outmd5.txt
 
             echo "------------------------------------------------------"
             echo "Test-running Singularity (\"$FLOW\")"
             echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ../common/run.py \
+            cd ${FLOWDIR} && ../../src/run.py \
                 --input ../common/accessions.txt \
                 --image docker://${IMAGE} \
                 --ini ~/.recount/cluster_singularity.ini \
@@ -216,13 +216,13 @@ Vagrant.configure("2") do |config|
             else
                 echo "===SAD ERROR running ${IMAGE} in Singularity"
             fi
-            find /work/recount-temp-singularity/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
-            cat ${FLOWDIR}/outmd5.txt
+            #find /work/recount-temp-singularity/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
+            #cat ${FLOWDIR}/outmd5.txt
         done
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "minio image", inline: <<-SHELL
-        cd /work/recount-pump/docker/minio && sudo ./build.sh && sudo ./push.sh
+        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
         if [ $? -eq 0 ] ; then
             echo "===HAPPY benlangmead/recount-minio built and pushed"
         else
@@ -231,11 +231,16 @@ Vagrant.configure("2") do |config|
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "integration test", inline: <<-SHELL
-        cd /work/recount-pump && ./integration_test.sh
-        if [ $? -eq 0 ] ; then
-            echo "===HAPPY integration tests passed"
+        export PATH="$PATH:/usr/local/bin"
+        if [ -n "$(which docker-compose)" -a -x "$(which docker-compose)" ] ; then
+            cd /work/recount-pump && ./integration_test.sh
+            if [ $? -eq 0 ] ; then
+                echo "===HAPPY integration tests passed"
+            else
+                echo "===SAD one or more integrations tests FAILED"
+            fi
         else
-            echo "===SAD one or more integrations tests FAILED"
+            echo "ERROR No docker-compose!!!" && exit 1
         fi
     SHELL
 end
