added s3 upload and fixed bugs with singualrity run

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -39,6 +39,8 @@ Vagrant.configure("2") do |config|
     config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~ec2-user/.ssh/id_rsa"
     config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~ec2-user/.ssh/id_rsa.pub"
     config.vm.provision "file", source: "~/.docker/creds.txt", destination: "~ec2-user/.docker/creds.txt"
+    config.vm.provision "file", source: "~/.aws/credentials", destination: "~ec2-user/.aws/credentials"
+    config.vm.provision "file", source: "~/.aws/config", destination: "~ec2-user/.aws/config"
 
     config.vm.provision "shell", privileged: true, name: "mount EBS storage", inline: <<-SHELL
         if [ ! -d /work ] ; then
@@ -50,24 +52,24 @@ Vagrant.configure("2") do |config|
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
-        yum install -q -y git wget gcc g++
+        yum install -q -y git wget gcc g++ aws-cli
     SHELL
-        
+         
     config.vm.provision "shell", privileged: true, name: "install docker-compose", inline: <<-SHELL
         echo "Install docker-compose"
         curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
         chmod +x /usr/local/bin/docker-compose
     SHELL
         
-    config.vm.provision "shell", privileged: true, name: "install Singularity", inline: <<-SHELL
+    config.vm.provision "shell", privileged: false, name: "install Singularity", inline: <<-SHELL
         echo "Install Singualrity"
         wget -q https://github.com/singularityware/singularity/releases/download/2.3.1/singularity-2.3.1.tar.gz
         tar xf singularity-2.3.1.tar.gz
         cd singularity-2.3.1 && \
             ./configure --prefix=/usr/local > /dev/null && \
-            make > /dev/null && make install > /dev/null && \
+            make > /dev/null && sudo make install > /dev/null && \
             cd .. && \
-            rm -rf singularity-2.3.1
+            rm -rf singularity-2.3.1 singularity-2.3.1.tar.gz
     SHELL
     
     config.vm.provision "shell", privileged: false, name: "setup ssh for git", inline: <<-SHELL
@@ -84,12 +86,12 @@ Vagrant.configure("2") do |config|
     SHELL
         
     config.vm.provision "shell", privileged: false, name: "docker login", inline: <<-SHELL
-        docker login -u $(cut -d' ' -f1 ~/.docker/creds.txt) \
-                     -p $(cut -d' ' -f2 ~/.docker/creds.txt)
+        docker login quay.io -u $(cut -d' ' -f1 ~/.docker/creds.txt) \
+                             -p $(cut -d' ' -f2 ~/.docker/creds.txt)
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "recount-pump image", inline: <<-SHELL
-        cd /work/recount-pump && ./build.sh && ./push.sh > /dev/null
+        cd /work/recount-pump && ./build.sh && ./push.sh
         if [ $? -eq 0 ] ; then
             echo "===HAPPY benlangmead/recount-pump built and pushed"
         else
@@ -98,13 +100,13 @@ Vagrant.configure("2") do |config|
     SHELL
         
     config.vm.provision "shell", privileged: false, name: "analysis images", inline: <<-SHELL
-        mkdir -p /work/recount-temp /work/recount-ref
-        cd /work/recount-ref && sh /work/recount-pump/workflow/prep_test.sh
+        FLOWBASE="/work/recount-pump/workflow"
         export RECOUNT_REF=/work/recount-ref
-        export RECOUNT_TEMP=/work/recount-temp
+        mkdir -p ${RECOUNT_REF}
+        cd ${RECOUNT_REF} && ${FLOWBASE}/prep_test.sh
         
         for FLOW in rna-seq-lite-nf rna-seq ; do
-            FLOWDIR="/work/recount-pump/workflow/${FLOW}"
+            FLOWDIR="${FLOWBASE}/${FLOW}"
             IMAGE=$(cat ${FLOWDIR}/image.txt)
 
             echo "******************************************************"
@@ -115,7 +117,7 @@ Vagrant.configure("2") do |config|
             echo "------------------------------------------------------"
             echo "Building and pushing (\"$FLOW\")"
             echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ./build.sh && ./push.sh > /dev/null
+            cd ${FLOWDIR} && ./build.sh && ./push.sh
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY ${IMAGE} built and pushed"
             else
@@ -125,17 +127,18 @@ Vagrant.configure("2") do |config|
             echo "------------------------------------------------------"
             echo "Test-running Docker (\"$FLOW\")"
             echo "------------------------------------------------------"
-            mkdir -p /tmp/input /tmp/output
-            cp ${FLOWDIR}/accessions.txt /tmp/input/
-            cd ${FLOWDIR} && ./dockrun.sh /tmp/input /tmp/output
+            export RECOUNT_TEMP=/work/recount-temp-docker-${FLOW}
+            mkdir -p ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output
+            chmod a+rwx ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output
+            cp ${FLOWDIR}/accessions.txt ${RECOUNT_TEMP}/input/
+            cd ${FLOWDIR} && ./dockrun.sh ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY ${IMAGE} ran in Docker"
             else
                 echo "===SAD ERROR running ${IMAGE} in Docker"
             fi
-            find /tmp/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
+            find ${RECOUNT_TEMP}/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
             cat ${FLOWDIR}/outmd5.txt
-            rm -rf /tmp/input /tmp/output
 
             echo "------------------------------------------------------"
             echo "Converting to Singularity (\"$FLOW\")"
@@ -152,22 +155,31 @@ Vagrant.configure("2") do |config|
             echo "------------------------------------------------------"
             echo "Test-running Singularity (\"$FLOW\")"
             echo "------------------------------------------------------"
-            mkdir -p /tmp/input /tmp/output
-            cp ${FLOWDIR}/accessions.txt /tmp/input/
-            cd ${FLOWDIR} && ./singrun.sh vagrant-test /tmp/input /tmp/output -i *.img
+            export RECOUNT_TEMP=/work/recount-temp-singularity-${FLOW}
+            mkdir -p ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output
+            chmod a+rwx ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output
+            cp ${FLOWDIR}/accessions.txt ${RECOUNT_TEMP}/input/
+            cd ${FLOWDIR} && ./singrun.sh vagrant-test ${RECOUNT_TEMP}/input ${RECOUNT_TEMP}/output -i *.img
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY ${IMAGE} ran in Singularity"
+                gzip *.img
+                aws s3 cp --quiet --acl public-read *.img.gz s3://recount-pump/image/
+                if [ $? -eq 0 ] ; then
+                    echo "===HAPPY ${IMAGE} copied to s3://recount-pump/image/"
+                else
+                    echo "===SAD ${IMAGE} could not be copied to s3://recount-pump/image/"
+                fi
+                rm -f *.img.gz
             else
                 echo "===SAD ERROR running ${IMAGE} in Singularity"
             fi
-            find /tmp/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
+            find ${RECOUNT_TEMP}/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
             cat ${FLOWDIR}/outmd5.txt
-            rm -rf /tmp/input /tmp/output
         done
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "minio image", inline: <<-SHELL
-        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh > /dev/null
+        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
         if [ $? -eq 0 ] ; then
             echo "===HAPPY benlangmead/recount-minio built and pushed"
         else
