new singularity/running regime

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -94,11 +94,14 @@ Vagrant.configure("2") do |config|
     SHELL
 
     config.vm.provision "shell", privileged: false, name: "recount-pump image", inline: <<-SHELL
-        cd /work/recount-pump && ./build.sh && ./push.sh
-        if [ $? -eq 0 ] ; then
-            echo "===HAPPY benlangmead/recount-pump built and pushed"
-        else
-            echo "===SAD ERROR building and/or pushing benlangmead/recount-pump"
+        SKIP_BUILD=0
+        if [ ${SKIP_BUILD} = 0 ] ; then
+            cd /work/recount-pump && ./build.sh && ./push.sh
+            if [ $? -eq 0 ] ; then
+                echo "===HAPPY benlangmead/recount-pump built and pushed"
+            else
+                echo "===SAD ERROR building and/or pushing benlangmead/recount-pump"
+            fi
         fi
     SHELL
 
@@ -131,7 +134,7 @@ Vagrant.configure("2") do |config|
         export RECOUNT_REF=/work/recount-ref
         mkdir -p ${RECOUNT_REF}
         cd ${RECOUNT_REF} && ${FLOWBASE}/prep_test.sh
-        
+        SKIP_BUILD=0
         for FLOW in rna-seq-lite-nf ; do
             FLOWDIR="${FLOWBASE}/${FLOW}"
             IMAGE=$(cat ${FLOWDIR}/image.txt)
@@ -141,20 +144,22 @@ Vagrant.configure("2") do |config|
             echo "              image: \"${IMAGE}\""
             echo "******************************************************"
 
-            echo "------------------------------------------------------"
-            echo "Building and pushing (\"$FLOW\")"
-            echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ../common/build.sh && ../common/push.sh
-            if [ $? -eq 0 ] ; then
-                echo "===HAPPY ${IMAGE} built and pushed"
-            else
-                echo "===SAD ERROR building and/or pushing ${IMAGE}"
+            if [ ${SKIP_BUILD} = 0 ] ; then
+                echo "------------------------------------------------------"
+                echo "Building and pushing (\"$FLOW\")"
+                echo "------------------------------------------------------"
+                cd ${FLOWDIR} && ../common/build.sh && ../common/push.sh
+                if [ $? -eq 0 ] ; then
+                    echo "===HAPPY ${IMAGE} built and pushed"
+                else
+                    echo "===SAD ERROR building and/or pushing ${IMAGE}"
+                fi
             fi
 
             echo "------------------------------------------------------"
             echo "Test-running Docker (\"$FLOW\")"
             echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ./run.py \
+            cd ${FLOWDIR} && ../common/run.py \
                 --input ../common/accessions.txt \
                 --image ${IMAGE} \
                 --docker \
@@ -171,7 +176,7 @@ Vagrant.configure("2") do |config|
             echo "------------------------------------------------------"
             echo "Test-running Singularity (\"$FLOW\")"
             echo "------------------------------------------------------"
-            cd ${FLOWDIR} && ./run.py \
+            cd ${FLOWDIR} && ../common/run.py \
                 --input ../common/accessions.txt \
                 --image ${IMAGE} \
                 --singularity \
