move vagrant_run up a directory so it's shared

diff --git a/vagrant/build_integration/Vagrantfile b/vagrant/build_integration/Vagrantfile
--- a/vagrant/build_integration/Vagrantfile
+++ b/vagrant/build_integration/Vagrantfile
@@ -67,7 +67,7 @@ Vagrant.configure("2") do |config|
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
-        yum install -q -y git aws-cli singularity docker-compose
+        yum install -q -y git aws-cli singularity docker-compose gcc g++
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "install docker", inline: <<-SHELL
@@ -99,11 +99,6 @@ Vagrant.configure("2") do |config|
             -o /usr/bin/docker-compose
         chmod +x /usr/bin/docker-compose
     SHELL
-
-    config.vm.provision "shell", privileged: true, name: "install watchtower", inline: <<-SHELL
-        pip install watchtower==0.5.2
-        pip install docopt==0.6.2
-    SHELL
     
     config.vm.provision "shell", privileged: true, name: "setup ssh for git", inline: <<-SHELL
         echo "Host github.com"               > /root/.ssh/config
@@ -117,24 +112,35 @@ Vagrant.configure("2") do |config|
     config.vm.provision "shell", privileged: true, name: "clone recount", inline: <<-SHELL
         cd /work && git clone -q git@github.com:langmead-lab/recount-pump.git
     SHELL
-        
+
+    config.vm.provision "shell", privileged: true, name: "update pip", inline: <<-SHELL
+        pip install --upgrade pip
+    SHELL
+
+    config.vm.provision "shell", privileged: true, name: "install recount requirements", inline: <<-SHELL
+        python -m pip install -r /work/recount-pump/requirements.txt
+    SHELL
+
     config.vm.provision "shell", privileged: true, name: "docker login", inline: <<-SHELL
         docker login quay.io -u $(cut -d' ' -f1 /root/.docker/creds.txt) \
                              -p $(cut -d' ' -f2 /root/.docker/creds.txt)
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "minio image", inline: <<-SHELL
-        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
-        if [ $? -eq 0 ] ; then
-            echo "===HAPPY benlangmead/recount-minio built and pushed"
-        else
-            echo "===SAD ERROR building and/or pushing benlangmead/recount-minio"
+        SKIP_MINIO=1
+        if [ ${SKIP_MINIO} = 0 ] ; then
+            cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
+            if [ $? -eq 0 ] ; then
+                echo "===HAPPY benlangmead/recount-minio built and pushed"
+            else
+                echo "===SAD ERROR building and/or pushing benlangmead/recount-minio"
+            fi
         fi
     SHELL
 
     config.vm.provision "shell", privileged: true, name: "recount-pump image", inline: <<-SHELL
-        SKIP_BUILD=0
-        if [ ${SKIP_BUILD} = 0 ] ; then
+        SKIP_PUMP=1
+        if [ ${SKIP_PUMP} = 0 ] ; then
             cd /work/recount-pump && ./build.sh && ./push.sh
             if [ $? -eq 0 ] ; then
                 echo "===HAPPY benlangmead/recount-pump built and pushed"
